### ISSUE TITLE
How to add new NOS types

### ISSUE THREAD

**Issue by prathap-shetty** [btr1975/pyats-genie-command-parse#3]
Hi,
This lib is really good, nice work.
I got two questions:
- can I add a new NOS type to this module and if yes any pointers on how to? like JUNOS?
- does this module works with all the command parsers supported by the Genie parser lib or there are some cases this may not work?

Thank you
Prathap

**Comment by btr1975** [comment]
Hello @vnstech 

You can add other NOS's by updateing the variable 'supported_nos = {'nxos', 'ios', 'iosxe', 'iosxr'}' on line 55 of the file pyats_genie_command_parse/pyats_genie_command_parse.py

To see what all NOS's and commands these support you can look at https://developer.cisco.com/docs/genie-docs/

Really this library extracts out pyats yml requirements, and I only allowed IOS, NXOS, and IOS-XR cause those I could verify it works.  Let me know how it goes.

**Comment by btr1975** [comment]
Added the following to Version 1.2.7

```python
 supported_nos = {'aireos',
                  'apic',
                  'asa',
                  'bigip',
                  'cheetah',
                  'comware',
                  'dnac',
                  'gaia',
                  'ios',
                  'iosxe',
                  'iosxr',
                  'ironware',
                  'junos',
                  'linux',
                  'nxos',
                  'sros',
                  'viptela'}
```

**Comment by prathap-shetty** [comment]
thanks, looks good
