### ISSUE TITLE
[Bug]: Exception when trying to parse output of "show access-list"

### ISSUE THREAD

**Issue by c3101** [btr1975/pyats-genie-command-parse#6]
### Describe Problem

When trying to parse output from a "show access-list" command using the parse_string method, the following exception occurs:

Could not find module_name for command show access-list for nos iosxe from genie: Parser Output is empty

```
            parser = GenieCommandParse(nos="iosxe")
            parsed_data = parser.parse_string(
                show_command="show access-list", show_output_data=output
            )
            print(parsed_data)
```

I also tried nos="ios", but this made no difference.
python 3.11.8

### Version

1.3.9

**Comment by btr1975** [comment]
This is not a bug.  That command is not in the Genie parser.  here is the source.

https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_acl.py

**Comment by btr1975** [comment]
The correct command is show access-lists
